### ISSUE TITLE
服务器的/money pay指令相关问题

### ISSUE THREAD

**Issue by xingnengmao666** [sensen1234/SenCraft#1]
（这里是github，我不会yygq的放心吧）服务器从2022年下旬开始，不知为何/money pay变得不可用，这大大减少了瑞国办法工资的速度，我们现在只能使用一两个有pay权限的账户来发工资，导致了瑞国现在几乎不能颁发工资了，恳请森森尽快修复（麻烦了）~

**Comment by sensen1234** [comment]
服务器一直不支持/money pay转账，从2月5日SenCraft项目开服皆不可使用，系staff设定的特性
如需查看你的金币数，清输入/bal以查看金币数
-------------
SenCraft server does not support /money pay transfer, it is not available since February 5, when SenCraft project started, it is a feature set by the staff.
To check your number of money, enter /bal to check your money.

**Comment by sensen1234** [comment]
补充：过后（3天内）将修复部分player能越权使用money pay的bug

**Comment by xingnengmao666** [comment]
ok，麻烦了
